frontend/app.py
import sys
import traceback

from dotenv import load_dotenv
from flask import Flask

from config import Config
from errors import ConnectorError


def _load_config(app: Flask):
    load_dotenv()

    app.config.from_object(Config)
    return app


def _register_blueprints(app: Flask):
    from views.hotel_routes import hotels_bp

    app.register_blueprint(hotels_bp)
    return app


def _register_error_handlers(app: Flask):
    @app.errorhandler(404)
    def handle_404(error: Exception):
        return "Page Not Found", 404

    @app.errorhandler(405)
    def handle_405(error: Exception):
        return "Method Not Allowed", 405

    @app.errorhandler(ConnectorError)
    def handle_connector_error(error: ConnectorError):
        return f"Upstream Service Error: {error.error_json}", error.status_code

    @app.errorhandler(Exception)
    def handle_unexpected_errors(error):
        etype, value, tb = sys.exc_info()
        print(traceback.print_exception(etype, value, tb))
        return "Internal Server Error", 500

    return app


def _register_healthcheck(app: Flask):
    @app.get("/ping")
    def ping():
        return "pong"

    return app


def create_app():
    app = Flask(__name__)

    app = _load_config(app)

    app = _register_blueprints(app)
    app = _register_error_handlers(app)
    app = _register_healthcheck(app)

    return app


if __name__ == "__main__":
    app = create_app()
    app.run()

frontend/views/hotel_routes.py
from flask import Blueprint, request, render_template, render_template_string
from services.hotel_service import HotelService


hotels_bp = Blueprint(
    "hotels",
    __name__,
    url_prefix="/hotels",
    template_folder="templates",
)


@hotels_bp.get("/")
def index():
    return render_template("index.html")


@hotels_bp.get("/search")
def render_search_hotels():
    return render_template("hotel_search.html")


@hotels_bp.post("/search")
def search_hotels():
    page = int(request.form.get("page") or 1)
    limit = int(request.form.get("limit") or 10)
    keyword = request.form.get("keyword", "").strip()
    if len(keyword) < 3:
        return render_template(
            "hotel_search.html",
            error="Search term must be at least 3 characters long",
        )

    results = HotelService().search(keyword=keyword, page=page, limit=limit)

    return render_template(
        "results.html",
        results=results,
        keyword=keyword,
        current_page=page,
        limit=limit,
        context="search",
    )


@hotels_bp.get("/browse")
def browse_hotels():
    page = int(request.args.get("page") or 1)
    limit = int(request.args.get("limit") or 10)

    results = HotelService().browse(page=page, limit=limit)

    return render_template(
        "results.html",
        results=results,
        current_page=page,
        limit=limit,
        context="browse",
    )

frontend/templates/hotel_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Search</title>
    <style>
        #error-msg {
            color: red;
        }
    </style>
</head>
<body>
    <h3>Search for hotels</h3>
    <p>Any hotel that contains your search term in name, city or country will be listed</p>
    <p>Search term needs to be at least 3 characters long</p>
    <form action="{{ url_for('hotels.search_hotels') }}" method="POST">
        <label for="keyword">Search</label>
        <br>
        <input type="text" name="keyword" placeholder="inn" required>
        {% if error %}
            <p id="error-msg">{{ error }}</p>
        {% endif %}
        <label for="keyword">How many results per page?</label>
        <br>
        <input type="text" name="limit" placeholder="10">
        <br>
        <br>
        <button type="submit">Search</button>
    </form>
    <br>
    <br>
    <br>
    <a href="{{ url_for('hotels.index') }}">Homepage</a>
</body>
</html>

frontend/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotels Browser</title>
</head>
<body>
    <a href="{{ url_for('hotels.browse_hotels')}}">Browse Hotels</a>
    <br>
    <a href="{{ url_for('hotels.render_search_hotels')}}">Search Hotels</a>
</body>
</html>

frontend/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    <style>
        table, td, th {
            border: 1px solid black;
            padding: 5px;
        }
        #form-prev, #form-next {
            display: inline-block;
        }
    </style>
</head>
<body>
    {% if context == "search" %}
        <h2>Search results including "{{ keyword }}"</h2>
    {%else %}
        <h2>All Available Hotels</h2>
    {% endif %}

        <table>
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>City</th>
            <th>Country</th>
        </thead>
        <tbody>
            {% for res in results["hotels"] %}
                <tr>
                    <td>{{ res.id }}</td>
                    <td>{{ res.name }}</td>
                    <td>{{ res.city }}</td>
                    <td>{{ res.country }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>

    {% if current_page > 1 %}
        <form action="" method={% if context == "search" %} "POST" {% else %} "GET" {% endif %} id="form-prev">
            <input type="text" name="page" value="{{ current_page - 1 }}" hidden>
            <input type="text" name="limit" value="{{ limit }}" hidden>
            {% if context == "search" %}
                <input type="text" name="keyword" value="{{ keyword }}" hidden>
            {% endif %}
            <button type="submit">Prev</button>
        </form>
    {% endif %}

    {% if results["hotels"] | length == limit %}
        <form action="" method={% if context == "search" %} "POST" {% else %} "GET" {% endif %} id="form-next">
            <input type="text" name="page" value="{{ current_page + 1 }}" hidden>
            <input type="text" name="limit" value="{{ limit }}" hidden>
            {% if context == "search" %}
                <input type="text" name="keyword" value="{{ keyword }}" hidden>
            {% endif %}
            <button type="submit">Next</button>
        </form>
    {% endif %}

    <br>
    <br>
    <br>
    {% if context == "search" %}
        <a href="{{ url_for('hotels.render_search_hotels') }}">Back to Search</a>
        <br>
    {% endif %}

    <a href="{{ url_for('hotels.index') }}">Homepage</a>

</body>
</html>